language: java
jdk:
    - oraclejdk8
before_install: "git clone -b travis-ci-settings `git config --get remote.origin.url` travis"
script:
    - "mvn test -B"
    - "mvn -X -e --settings travis/settings.xml sonar:sonar -Dsonar.verbose=true"
